package cn.hust.spike.dao;

import cn.hust.spike.entity.ProductStock;
import org.apache.ibatis.annotations.Param;

public interface ProductStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbggenerated
     */
    int insert(ProductStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbggenerated
     */
    int insertSelective(ProductStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbggenerated
     */
    ProductStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_stock
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductStock record);


    ProductStock selectByProductId(Integer productId);

    int decreaseStock(@Param( "productId") Integer productId,@Param("amount") Integer amount);


}